version: 0.4.0.{build}

environment:
    global:
        SDL_AUDIODRIVER: "disk"
        MSYSTEM: MINGW64
        # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
        # /E:ON and /V:ON options are not enabled in the batch script intepreter
        # See: http://stackoverflow.com/a/13751649/163740
        #WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"

    matrix:
        - MSYS2_ARCH: i686
          MSYSTEM: MINGW32
          MSYSTEM_: mingw32
          PKG_PREFIX: "mingw-w64-i686"
          PYTHON: "C:\\Python27"
          PYTHON_VERSION: "python2"

        - MSYS2_ARCH: x86_64
          MSYSTEM: MINGW64
          MSYSTEM_: mingw64
          PKG_PREFIX: "mingw-w64-x86_64"
          PYTHON: "C:\\Python27-x64"
          PYTHON_VERSION: "python2"

        - MSYS2_ARCH: i686
          MSYSTEM: MINGW32
          MSYSTEM_: mingw32
          PKG_PREFIX: "mingw-w64-i686"
          PYTHON: "C:\\Python36"
          PYTHON_VERSION: "python3"

        - MSYS2_ARCH: x86_64
          MSYSTEM: MINGW64
          MSYSTEM_: mingw64
          PKG_PREFIX: "mingw-w64-x86_64"
          PYTHON: "C:\\Python36-x64"
          PYTHON_VERSION: "python3"

#        - PYTHON: "C:\\Python27"
#          PYTHON_ARCH: 32
#          MSVC_VERSION: "Visual Studio 10"
#
#        - PYTHON: "C:\\Python36"
#          PYTHON_ARCH: 32
#          MSVC_VERSION: "Visual Studio 14"
#
#        - PYTHON: "C:\\Python27-x64"
#          PYTHON_ARCH: 64
#          MSVC_VERSION: "Visual Studio 10 Win64"
#
#        - PYTHON: "C:\\Python36-x64"
#          PYTHON_ARCH: 64
#          MSVC_VERSION: "Visual Studio 14 Win64"

#matrix:
#    fast_finish: true

build: off

init:
    - "ECHO %PYTHON% %PYTHON_ARCH% %MSVC_VERSION%"
#    - "%PYTHON%\\python.exe --version"
    - "SET PATH=C:\\msys64\\%MSYSTEM%\\bin;C:\\msys64\\usr\\bin;C:\\msys64\\bin;%PATH%"

install:
    # Put Python in PATH
    #- "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

    # download and unzip sources
    # https://github.com/vladimirgamalyan/sdl2_msvc_builds/blob/master/appveyor.yml
    # SDL 1.2.15 dll
    #- appveyor DownloadFile https://www.libsdl.org/release/SDL-1.2.15-win32.zip
    #- 7z x SDL-1.2.15-win32.zip > nul

    # SDL mixer 1.2.12
    # https://www.libsdl.org/projects/SDL_mixer/release/SDL_mixer-1.2.12-win32.zip
    # https://www.libsdl.org/projects/SDL_mixer/release/SDL_mixer-1.2.12-win32-x64.zip

    # SDL image 1.2.12
    # https://www.libsdl.org/projects/SDL_image/release/SDL_image-1.2.12-win32.zip
    # https://www.libsdl.org/projects/SDL_image/release/SDL_image-1.2.12-win32-x64.zip

    # SDL ttf 2.0.11
    # https://www.libsdl.org/projects/SDL_ttf/release/SDL_ttf-2.0.11-win32.zip
    # https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14-win32-x64.zip

    # Soundtouch 2.0.0
    # https://www.surina.net/soundtouch/soundtouch_dll-2.0.0.zip


    # system dependencies
    - "echo %PKG_PREFIX%"
    - pacman -Syu --noconfirm
    - pacman --noconfirm --needed -Sy bash pacman pacman-mirrors msys2-runtime msys2-runtime-devel
    - bash -lc "pacman -S --noconfirm --needed --noprogressbar
        autoconf
        automake
        base-devel
        %PKG_PREFIX%-toolchain
        %PKG_PREFIX%-%PYTHON_VERSION%
        %PKG_PREFIX%-%PYTHON_VERSION%-pip
        %PKG_PREFIX%-pkg-config
        %PKG_PREFIX%-portmidi
        %PKG_PREFIX%-libvorbis
        %PKG_PREFIX%-libtheora
        %PKG_PREFIX%-SDL
        %PKG_PREFIX%-SDL_image
        %PKG_PREFIX%-SDL_mixer
        %PKG_PREFIX%-SDL_ttf
        %PKG_PREFIX%-soundtouch
        %PKG_PREFIX%-libiconv"
#    - bash -lc "ls C:/msys64/mingw32/bin/"
#    - bash -lc "ls C:/msys64/mingw64/bin/"
#    - bash -lc "ls C:/msys64/usr/bin/"

    # python dependencies
    - bash -lc "%PYTHON_VERSION% --version"
    - bash -lc "%PYTHON_VERSION% -m pip install -U pip" # Upgrade pip
    - bash -lc "%PYTHON_VERSION% -m pip install wheel"
    - bash -lc "%PYTHON_VERSION% -m pip install cython"

    # git submodule
    - "git submodule update --init --recursive"

    # link
    - bash -lc "ln -s C:/msys64/%MSYSTEM_%/bin/libiconv-2.dll C:/msys64/%MSYSTEM_%/bin/iconv.dll"
    - bash -lc "ln -s C:/msys64/%MSYSTEM_%/bin/libSoundTouch-1.dll C:/msys64/%MSYSTEM_%/bin/libSoundTouch-0.dll"
    - bash -lc "ln -s C:/msys64/%MSYSTEM_%/bin/libSDL_mixer-1-2-0.dll C:/msys64/%MSYSTEM_%/bin/SDL_mixer.dll"
    - bash -lc "ln -s C:/msys64/%MSYSTEM_% C:/projects/fretwork/win32/deps"

      ## soundtouch-c
      #- bash -lc "%MSYS2_ARCH%-w64-mingw32-pkg-config --cflags glib-2.0 soundtouch"
    - bash -lc "%MSYS2_ARCH%-w64-mingw32-g++ -g -O2 -W -Wall `%MSYS2_ARCH%-w64-mingw32-pkg-config --cflags glib-2.0 soundtouch` -fexceptions -fno-rtti -c -o soundtouch-c.o C:/projects/fretwork/fretwork/mixstream/soundtouch-c.cpp"
    - bash -lc "ls"
    - bash -lc "pwd"
    - bash -lc "rm -rf C:/projects/fretwork/win32/deps/lib/soundtouch-c.lib"
    - bash -lc "%MSYS2_ARCH%-w64-mingw32-gcc-ar cru C:/projects/fretwork/win32/deps/lib/soundtouch-c.lib soundtouch-c.o"
    - bash -lc "%MSYS2_ARCH%-w64-mingw32-gcc-ranlib C:/projects/fretwork/win32/deps/lib/soundtouch-c.lib"
    - bash -lc "rm -rf C:/projects/fretwork/win32/deps/lib/soundtouch-c.o"
    - bash -lc "cp C:/projects/fretwork/win32/deps/lib/soundtouch-c.lib C:/msys64/%MSYSTEM_%/lib"
    - bash -lc "ls C:/projects/fretwork/fretwork/mixstream/"

    # debug
    - bash -lc "ls C:/projects/fretwork/win32/deps/lib/"
    - bash -lc "ls C:/projects/fretwork/win32/deps/bin/"
    - "ECHO C:/msys64/%MSYSTEM_%/lib/"
    - bash -lc "ls C:/msys64/%MSYSTEM_%/lib/"

    # path
#    - "SET PATH=C:\\projects\\fretwork\\win32\\deps\\bin;%PATH%"
#    - "SET PATH=C:\\projects\\fretwork\\win32\\deps\\lib;%PATH%"

build_script:
    - bash -lc "cd C:/projects/fretwork && C:/projects/fretwork/win32/deps/bin/%PYTHON_VERSION% setup.py build_ext --inplace --force"
    - bash -lc "cd C:/projects/fretwork && C:/projects/fretwork/win32/deps/bin/%PYTHON_VERSION% setup.py sdist"
    - bash -lc "ls C:/projects/fretwork/*"
    - bash -lc "cd C:/projects/fretwork && C:/projects/fretwork/win32/deps/bin/%PYTHON_VERSION% setup.py bdist_wheel"

#test_script:
#    - bash -lc "cd C:/projects/fretwork && %PYTHON_VERSION% -m pip install dist/*.whl"
#    - bash -lc "cd C:/projects/fretwork && %PYTHON_VERSION% -m pip install dist/fretwork-0.3.0.tar.gz"
#    - bash -lc "cd C:/projects/fretwork && %PYTHON_VERSION% -m pip install pytest"
#    - bash -lc "cd C:/projects/fretwork && rm -rf fretwork"
#    - bash -lc "cd C:/projects/fretwork && pytest tests"
#    - bash -lc "cd C:/projects/fretwork && python -c 'from fretwork.mixstream import *'"

artifacts:
    - path: dist\*
    #- path: win32\deps\
